In [1]:
import gensim

C:\Users\Amey\Anaconda3\lib\site-packages\gensim\utils.py:1197: UserWarning: detected Windows; aliasing chunkize to chunkize_serial
  warnings.warn("detected Windows; aliasing chunkize to chunkize_serial")


In [90]:
import pandas as pd
import nltk
import spacy
from string import punctuation
from nltk.tokenize import word_tokenize
from nltk.stem import LancasterStemmer
from nltk.corpus import stopwords
from sklearn.feature_extraction.text import TfidfVectorizer
import collections
import nltk
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.decomposition import TruncatedSVD
import nltk
from nltk.corpus import stopwords
from string import punctuation
nltk.download('stopwords')
nltk.download('punkt')
stop_words = stopwords.words('english')
from string import punctuation
custom = stop_words+list(punctuation)
from nltk.stem import WordNetLemmatizer
wordnet_lemmatizer = WordNetLemmatizer()
nltk.download('wordnet')
import warnings
warnings.filterwarnings("ignore")

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Amey\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\Amey\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\Amey\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


In [19]:
data = pd.read_csv(r"G:\study\Natural Language processing\nlp_class\Consumer_Complaints.csv")

C:\Users\Amey\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3057: DtypeWarning: Columns (5,6,11,16) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


In [20]:
data=data.dropna()

In [21]:
data = data.iloc[:10,:]

In [22]:
data1 = data.copy()

In [23]:
data1=data[['Consumer complaint narrative']]

In [24]:
data1.head()

Consumer complaint narrative
562059  A charge was made by a company making false cl...
562662  This debt is beyond the Maryland Statute of Li...
563174  My personal belongings and vehicle were stolen...
563593  This complaint is necessary to ensure the reco...
563760  I was taken to the hospital while   XXXX   XXX...

In [25]:
ls = LancasterStemmer()

In [26]:
corpus=data1['Consumer complaint narrative'].tolist()

In [27]:
stuff_to_be_removed = list(stopwords.words("english"))+list(punctuation)

In [28]:
def prepross(s):
    words = s.lower()
    #print(words)
    words = word_tokenize(words)
    #print(words)
    words = [x for x in words if x not in stuff_to_be_removed]
    #print(words)
    words = [ls.stem(x) for x in words]
    words = [" ".join(words)]
    return words

In [29]:
final=[]
for i in range(len(corpus)):
    z= prepross(corpus[i])
    final.append(z)

In [47]:
final[i][0]

'charg mad company mak fals claim produc also ad addit produc purchas bank hon disput charg absurd lat fee bal paid'

In [48]:
#text = [word for line in final for word in line.split()]
text=[]
for i in range(len(final)):
    for word in final[i][0].split():
        text.append(word)

In [30]:
new_df = pd.DataFrame(final)
new_df.columns = ['Consumer complaint narrative']

In [31]:
new_df.head()

Consumer complaint narrative
0  charg mad company mak fals claim produc also a...
1  debt beyond maryland statut limit illeg debt c...
2  person belong vehic stol xxxx =my lock brok po...
3  complaint necess ens recovery collect firm 's ...
4  tak hospit xxxx xxxx xxxx xxxx xxxx xxxx xxxx ...

In [16]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf = TfidfVectorizer()

In [17]:
vector = tfidf.fit_transform(new_df['Consumer complaint narrative'])

In [18]:
vector.shape

(100, 1295)

In [79]:
vector[0].toarray()

array([[0., 0., 0., ..., 0., 0., 0.]])

In [80]:
vector[0][0].toarray()

array([[0., 0., 0., ..., 0., 0., 0.]])

In [68]:
final1=pd.DataFrame(vector.toarray())

In [70]:
final1.shape

(100, 1957)

In [63]:
from sklearn.decomposition import TruncatedSVD

In [64]:
lsa = TruncatedSVD(n_components=3,n_iter=60)

In [65]:
lsa.fit(vector)

TruncatedSVD(algorithm='randomized', n_components=3, n_iter=60,
             random_state=None, tol=0.0)

In [66]:
len(lsa.components_[0])

1295

In [67]:
lsa.components_

array([[ 0.09280222,  0.00463801,  0.00882923, ...,  0.0013318 ,
         0.00294172,  0.01088053],
       [ 0.04350081, -0.00493068,  0.00417542, ...,  0.00027945,
        -0.00860692,  0.01269007],
       [ 0.1353849 ,  0.0065807 ,  0.03034708, ...,  0.00279956,
        -0.00046507, -0.02004785]])

In [68]:
lsa.explained_variance_

array([0.02165775, 0.0375576 , 0.02673777])

In [91]:
dataset = ["The amount of pollution is increasing day by day",
"The concert was just great", "I love to see Gordon Ramsay cook",
"Google is introducing a new technlogy", "AI robots are great example of great technology present today",
"All of us were singing in the concert", "We have launch campaigns to stop pollution and global warming"]

In [92]:
dataset

['The amount of pollution is increasing day by day',
 'The concert was just great',
 'I love to see Gordon Ramsay cook',
 'Google is introducing a new technlogy',
 'AI robots are great example of great technology present today',
 'All of us were singing in the concert',
 'We have launch campaigns to stop pollution and global warming']

In [93]:
import pandas as pd

In [94]:
import numpy as np

In [95]:
dataset = [line.lower() for  line in dataset]

NameError: name 'tok' is not defined

In [99]:
X = tfidf.fit_transform(dataset)

In [100]:
X.shape

(7, 42)

In [101]:
lsa = TruncatedSVD(n_components=4,n_iter=100)

In [102]:
lsa.fit(X)

TruncatedSVD(algorithm='randomized', n_components=4, n_iter=100,
             random_state=None, tol=0.0)

In [103]:
lsa.components_[0][0]

0.11696462486835726

In [104]:
words = tfidf.get_feature_names()

In [105]:
c={}
def abc(d,j):
    d={}
    for i in range(len(lsa.components_[j])):
        d[words[i]] = lsa.components_[j][i]
    d=sorted(d, key=d.get, reverse=True)
    d=d[:10]
    return d

In [106]:
d0 = abc(c,0)
d1 = abc(c,1)
d2 = abc(c,2)
d3 = abc(c,3)

In [107]:
d0

['great', 'the', 'concert', 'of', 'just', 'was', 'day', 'all', 'in', 'singing']

In [108]:
d1

['to',
 'pollution',
 'day',
 'is',
 'cook',
 'gordon',
 'love',
 'ramsay',
 'see',
 'and']

In [109]:
d2

['is',
 'google',
 'introducing',
 'new',
 'technlogy',
 'day',
 'amount',
 'by',
 'increasing',
 'of']

In [110]:
d3

['great',
 'google',
 'introducing',
 'new',
 'technlogy',
 'are',
 'example',
 'present',
 'robots',
 'technology']

In [111]:
for i,y in enumerate(lsa.components_):
    componentwords = zip(words, y)
    sortedComponentwords = sorted(componentwords, key = lambda x: x[1],
                                reverse=True)
    sortedComponentwords = sortedComponentwords[:10]
    print ("\nTopic", i, ";")
    for x in sortedComponentwords:
        print (x)


Topic 0 ;
('great', 0.4098416235534007)
('the', 0.37872314722187916)
('concert', 0.3574166811716594)
('of', 0.2773738067325902)
('just', 0.2598047527022688)
('was', 0.2598047527022688)
('day', 0.2063766936709453)
('all', 0.1707732032489237)
('in', 0.1707732032489237)
('singing', 0.1707732032489237)

Topic 1 ;
('to', 0.3218414494137703)
('pollution', 0.26410761357197976)
('day', 0.24902077191893163)
('is', 0.2290114925683949)
('cook', 0.1940620278819667)
('gordon', 0.1940620278819667)
('love', 0.1940620278819667)
('ramsay', 0.1940620278819667)
('see', 0.1940620278819667)
('and', 0.193658637462118)

Topic 2 ;
('is', 0.34424073742032224)
('google', 0.29368746403512386)
('introducing', 0.29368746403512386)
('new', 0.29368746403512386)
('technlogy', 0.29368746403512386)
('day', 0.2420350065062839)
('amount', 0.12101750325314209)
('by', 0.12101750325314195)
('increasing', 0.12101750325314195)
('of', 0.0460701545850063)

Topic 3 ;
('great', 0.36097341569294356)
('google', 0.21834424295923002

In [112]:
lsa = TruncatedSVD(n_components=3,n_iter=100)

In [113]:
lsa.fit(vector)

TruncatedSVD(algorithm='randomized', n_components=3, n_iter=100,
             random_state=None, tol=0.0)

In [114]:
words = tfidf.get_feature_names()

In [115]:
words

['ai',
 'all',
 'amount',
 'and',
 'are',
 'by',
 'campaigns',
 'concert',
 'cook',
 'day',
 'example',
 'global',
 'google',
 'gordon',
 'great',
 'have',
 'in',
 'increasing',
 'introducing',
 'is',
 'just',
 'launch',
 'love',
 'new',
 'of',
 'pollution',
 'present',
 'ramsay',
 'robots',
 'see',
 'singing',
 'stop',
 'technlogy',
 'technology',
 'the',
 'to',
 'today',
 'us',
 'warming',
 'was',
 'we',
 'were']

In [116]:
for i,y in enumerate(lsa.components_):
    componentwords = zip(words, y)
    sortedComponentwords = sorted(componentwords, key = lambda x: x[1],
                                reverse=True)
    sortedComponentwords = sortedComponentwords[:10]
    print ("\nTopic", i, ";")
    for x in sortedComponentwords:
        print (x)


Topic 0 ;
('ai', 0.0928022218121584)
('pollution', 0.05287045736891479)
('us', 0.017688459454025994)
('google', 0.017411505722448112)
('day', 0.008985858938185123)
('amount', 0.008829227700539236)
('of', 0.008480530156183464)
('new', 0.00837043943340014)
('warming', 0.006871946761745564)
('have', 0.006768216053919551)

Topic 1 ;
('ai', 0.04350080976948647)
('us', 0.02079574274802273)
('of', 0.014330022987497486)
('google', 0.014089941601454634)
('pollution', 0.01406729586217281)
('today', 0.010350445676500277)
('technology', 0.009508829837328921)
('cook', 0.006897639224349192)
('in', 0.006681990792328114)
('present', 0.005740677323670909)

Topic 2 ;
('ai', 0.1353848960786917)
('google', 0.05315963132700794)
('warming', 0.03482486738108809)
('amount', 0.03034708131442759)
('in', 0.02156392137072954)
('increasing', 0.016607119111663786)
('see', 0.016607119111663786)
('is', 0.012985154073591874)
('by', 0.011258362712682459)
('example', 0.011258362712682459)


In [117]:
import gensim
def my_tokenizer(s):
    s = s.lower()
    tokens = nltk.tokenize.word_tokenize(s)
    tokens = [t for t in tokens if len(t)>2] #remove words lesser than 2 in length
    tokens = [wordnet_lemmatizer.lemmatize(t) for t in tokens] #lemmatize words
    tokens = [t for t in tokens if t not in custom] #remove stopwords and punctuation
    tokens = [t for t in tokens if not any(c.isdigit() for c in t)] # remove digits
    return tokens

In [118]:
text = [my_tokenizer(s) for s in dataset]

In [119]:
from gensim.corpora import dictionary
from gensim import corpora
from pprint import pprint

In [120]:
id2word = corpora.Dictionary(text)
print(id2word)

Dictionary(27 unique tokens: ['amount', 'day', 'increasing', 'pollution', 'concert']...)


In [121]:
mycorpus = [id2word.doc2bow(a) for a in text]

In [122]:
mycorpus

[[(0, 1), (1, 2), (2, 1), (3, 1)],
 [(4, 1), (5, 1), (6, 1)],
 [(7, 1), (8, 1), (9, 1), (10, 1), (11, 1)],
 [(12, 1), (13, 1), (14, 1), (15, 1)],
 [(5, 2), (16, 1), (17, 1), (18, 1), (19, 1), (20, 1)],
 [(4, 1), (21, 1)],
 [(3, 1), (22, 1), (23, 1), (24, 1), (25, 1), (26, 1)]]

In [127]:
from gensim.test.utils import common_corpus, common_dictionary
from gensim.models.ldamodel import LdaModel
from gensim.models.coherencemodel import CoherenceModel

lda_model = gensim.models.ldamodel.LdaModel(corpus=mycorpus,
                                           id2word=id2word,
                                           num_topics=20, 
                                           random_state=100,
                                           update_every=1,
                                           chunksize=100,
                                           passes=10,
                                           alpha='auto',
                                           per_word_topics=True)

In [129]:
coherence_model_lda = CoherenceModel(model=lda_model, texts=text, dictionary=id2word, coherence='c_v')
coherence_lda = coherence_model_lda.get_coherence()
print('\nCoherence Score: ', coherence_lda)


Coherence Score:  0.5686642234772799


In [133]:
# Visualize the topics
import pyLDAvis
from pyLDAvis import gensim
pyLDAvis.enable_notebook()
vis = pyLDAvis.gensim.prepare(lda_model, mycorpus, id2word)
vis

TypeError: Object of type complex is not JSON serializable

PreparedData(topic_coordinates=                                 x                            y  topics  \
topic                                                                     
5         (0.18801443699018403+0j)   (-0.019111898877925734+0j)       1   
8        (-0.21413382303742434+0j)     (0.06324909302949697+0j)       2   
19       (0.018041131365856142+0j)    (-0.26296288160287734+0j)       3   
3        (-0.12654627758717757+0j)    (0.016969040635350055+0j)       4   
9          (0.1336601552031702+0j)     (0.13465749118331224+0j)       5   
2         (0.05204106756977736+0j)     (0.11268613755560936+0j)       6   
14      (-0.003648335036027546+0j)  (-0.0032490701373545997+0j)       7   
13     (-0.0036483350360275316+0j)    (-0.00324907013735462+0j)       8   
12      (-0.003648335036027542+0j)   (-0.003249070137354622+0j)       9   
11      (-0.003648335036027517+0j)  (-0.0032490701373546374+0j)      10   
10      (-0.003648335036027518+0j)  (-0.0032490701373546387+0j)      

In [ ]:
def compute_coherence_values(dictionary, corpus, texts, limit, start=2, step=3):
    """
    Compute c_v coherence for various number of topics

    Parameters:
    ----------
    dictionary : Gensim dictionary
    corpus : Gensim corpus
    texts : List of input texts
    limit : Max num of topics

    Returns:
    -------
    model_list : List of LDA topic models
    coherence_values : Coherence values corresponding to the LDA model with respective number of topics
    """
    coherence_values = []
    model_list = []
    for num_topics in range(start, limit, step):
        model = gensim.models.wrappers.LdaMallet(mallet_path, corpus=corpus, num_topics=num_topics, id2word=id2word)
        model_list.append(model)
        coherencemodel = CoherenceModel(model=model, texts=texts, dictionary=dictionary, coherence='c_v')
        coherence_values.append(coherencemodel.get_coherence())

    return model_list, coherence_values

In [ ]:
# Can take a long time to run.
model_list, coherence_values = compute_coherence_values(dictionary=id2word, corpus=corpus, texts=data_lemmatized, start=2, limit=40, step=6)

In [ ]:
# Show graph
limit=40; start=2; step=6;
x = range(start, limit, step)
plt.plot(x, coherence_values)
plt.xlabel("Num Topics")
plt.ylabel("Coherence score")
plt.legend(("coherence_values"), loc='best')
plt.show()